api:
  insecure: true
  dashboard: true
ping:
  entryPoint: traefik
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  ssh:
    address: ":22"
  traefik:
    address: ":8082"

providers:
  docker:
    exposedByDefault: false
    endpoint: "unix:///var/run/docker.sock"
    network: "dce-cloud-backend"
  file:
    directory: "/etc/traefik/config"
    watch: true

log:
  level: DEBUG
  format: json
  
accessLog:
  format: "json"
